apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # This PVC is for the MS SQL Server instance files
  name: mssql-instance-pvc
spec:
  storageClassName: vsan-default-storage-policy
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # This PVC is for the MS SQL Server data
  name: mssql-data-pvc
spec:
  storageClassName: vsan-default-storage-policy
  resources:
    requests:
      # These values are for up to 1,000 users per Workspace ONE Access 20.10 docs
      storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # This PVC is for the MS SQL Server log files
  name: mssql-logs-pvc
spec:
  storageClassName: vsan-default-storage-policy
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
