CREATE DATABASE WSOAccess
COLLATE Latin1_General_CS_AS;
ALTER DATABASE WSOAccess SET READ_COMMITTED_SNAPSHOT ON;
GO

BEGIN
CREATE LOGIN vidm WITH PASSWORD = N'SuperSecretPassword';
END
GO

USE WSOAccess; 
IF EXISTS (SELECT * FROM sys.database_principals WHERE name=N'vidm')
DROP USER [vidm]
GO

CREATE USER [vidm] FOR LOGIN [vidm]
WITH DEFAULT_SCHEMA=saas;
GO

CREATE SCHEMA saas AUTHORIZATION vidm
GRANT ALL ON DATABASE::WSOAccess TO vidm;
GO

ALTER ROLE [db_owner] ADD MEMBER vidm;
GO